name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build application
        run: |
          npm run build

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment --application-name abcs-of-aws --environment-name Abcs-of-aws-env --version-label ${{ github.sha }}
